### ISSUE TITLE
OpenTelemetry Metrics with Invalid types

### ISSUE THREAD

**Issue by meldsza** [openfga/python-sdk#117]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/python-sdk/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/python-sdk/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/python-sdk/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [Slack community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

Looks like the FGA Client Metrics have invalid types for client_id when running openfga with Preshared Keys. 
```sh
Failed to encode key fga-client.request.client_id: Invalid type <class 'NoneType'> of value None
```
This issue gets exacerbated when running opentelemetry with auto-instrumentation for logs enabled.

### Expectation

Expectation is that running OpenFGA SDK with Preshared Keys does not result in exceptions on opentelemetry

### Reproduction

1. Run OpenFGA with Pre-shared keys
2. Configure OpenFGA Python SDK with Pre-shared keys
3. Enable OpenTelemetry Auto-Instrumentation with Logging enabled
  ```python
  # Also add the below line to ensure the Logging auto-isntrumentation does not swallow logs and print it to stdout
 import logging
 import sys
 logging.getLogger().addHandler(logging.StreamHandler(sys.stdout))
  ```
5. Run the SDK for a while and make requests

### OpenFGA SDK version

0.6.1

### OpenFGA version

0.5.7

### OpenTelemetry Python Instrumentation Version
0.47b0

### SDK Configuration

```python
openfga_config = openfga_sdk.ClientConfiguration(
            api_url=url,
            store_id=storeid,
            credentials=Credentials(
                method="api_token",
                configuration=CredentialConfiguration(
                    api_token=token,
                ),
            ),
        )
client = openfga_sdk.OpenFgaClient(openfga_config)
```

### Logs

```sh
Failed to encode key fga-client.request.client_id: Invalid type <class 'NoneType'> of value None
Traceback (most recent call last):
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 111, in _encode_attributes
   pb2_attributes.append(_encode_key_value(key, value))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 92, in _encode_key_value
   return PB2KeyValue(key=key, value=_encode_value(value))
                                     ^^^^^^^^^^^^^^^^^^^^
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 88, in _encode_value
   raise Exception(f"Invalid type {type(value)} of value {value}")
Exception: Invalid type <class 'NoneType'> of value None
Failed to encode key fga-client.request.client_id: Invalid type <class 'NoneType'> of value None
Traceback (most recent call last):
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 111, in _encode_attributes
   pb2_attributes.append(_encode_key_value(key, value))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 92, in _encode_key_value
   return PB2KeyValue(key=key, value=_encode_value(value))
                                     ^^^^^^^^^^^^^^^^^^^^
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 88, in _encode_value
   raise Exception(f"Invalid type {type(value)} of value {value}")
Exception: Invalid type <class 'NoneType'> of value None
Failed to encode key fga-client.request.client_id: Invalid type <class 'NoneType'> of value None
Traceback (most recent call last):
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 111, in _encode_attributes
   pb2_attributes.append(_encode_key_value(key, value))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 92, in _encode_key_value
   return PB2KeyValue(key=key, value=_encode_value(value))
                                     ^^^^^^^^^^^^^^^^^^^^
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 88, in _encode_value
   raise Exception(f"Invalid type {type(value)} of value {value}")
Exception: Invalid type <class 'NoneType'> of value None
Failed to encode key fga-client.request.client_id: Invalid type <class 'NoneType'> of value None
Traceback (most recent call last):
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 111, in _encode_attributes
   pb2_attributes.append(_encode_key_value(key, value))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 92, in _encode_key_value
   return PB2KeyValue(key=key, value=_encode_value(value))
                                     ^^^^^^^^^^^^^^^^^^^^
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 88, in _encode_value
   raise Exception(f"Invalid type {type(value)} of value {value}")
Exception: Invalid type <class 'NoneType'> of value None
Failed to encode key fga-client.request.client_id: Invalid type <class 'NoneType'> of value None
Traceback (most recent call last):
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 111, in _encode_attributes
   pb2_attributes.append(_encode_key_value(key, value))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 92, in _encode_key_value
   return PB2KeyValue(key=key, value=_encode_value(value))
                                     ^^^^^^^^^^^^^^^^^^^^
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 88, in _encode_value
   raise Exception(f"Invalid type {type(value)} of value {value}")
Exception: Invalid type <class 'NoneType'> of value None
Failed to encode key fga-client.request.client_id: Invalid type <class 'NoneType'> of value None
Traceback (most recent call last):
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 111, in _encode_attributes
   pb2_attributes.append(_encode_key_value(key, value))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 92, in _encode_key_value
   return PB2KeyValue(key=key, value=_encode_value(value))
                                     ^^^^^^^^^^^^^^^^^^^^
 File "/otel-auto-instrumentation-python/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 88, in _encode_value
   raise Exception(f"Invalid type {type(value)} of value {value}")
Exception: Invalid type <class 'NoneType'> of value None
```

**Comment by meldsza** [comment]
Maybe a check for None would help here:
https://github.com/openfga/python-sdk/blob/e82545e8ae2bdd4064ce846d8eb4a11c95359e85/openfga_sdk/api_client.py#L315

**Comment by meldsza** [comment]
Do I have to raise a PR to this repo as well?

**Comment by jimmyjames** [comment]
> Do I have to raise a PR to this repo as well?

👋 hi @meldsza, apologies for the delayed response! Yes, we do need PRs in the client repos as well the generator repo. I just made #119 to get your fix synced to the SDK. Thanks again!
